# Basic Site Settings
locale                   : "en-US"
title                    : "Rohit Deshmukh"
title_separator          : "-"
name                     : &name "Rohit Deshmukh"
description              : &description "Data Scientist"
url                      : https://academicpages.github.io # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io" or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
